name: Generate semver tags

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: ${{ matrix.version }}
      - uses: actions/checkout@v1 # related: actions/checkout#290
      - name: Run generate_tag
        run: ./scripts/generate_tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
